name = "Developer Portfolio Plus"
license = "MIT"
licenselink = "https://github.com/bmyjacks/hugo-developer-portfolio-plus/blob/master/LICENSE"
description = "The enhanced edition of developer portfolio"
homepage = "https://github.com/bmyjacks/hugo-developer-portfolio-plus"
tags = ["portfolio", "developer", "responsive","uikit"]
features = ["uikit", "responsive", "features"]
min_version = "0.54.0"

[author]
    name = "bmyjacks"
    homepage = "https://www.bmyjacks.io"

